language: haskell
ghc: 7.8
addons:
  postgresql: "9.3"
notifications:
  slack: looprecur:z2nPS2Cfx2D33LE2obyU2FyQ
before_install:
  - createuser --superuser --no-password dbapi_test
  - createdb -O dbapi_test -U postgres dbapi_test
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install --force-yes happy-1.19.3 alex-3.1.3
  - export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.3/bin:$PATH
install:
  - curl http://bin.begriffs.com/dbapi/cabal-sandbox.tar.xz | tar xJ
  - chmod a+x .cabal-sandbox/bin/*
  - cabal sandbox init
  - cabal install --enable-test --dependencies-only
  - cabal install --enable-test
script:
  - cabal test --show-details=always --test-options="--color"
  - .cabal-sandbox/bin/hlint src/*.hs test/**/*.hs
cache:
  directories:
    - .cabal-sandbox
